### ISSUE TITLE
[FR] hoshi005 が参加

### ISSUE THREAD

**Issue by hoshi005** [rubydog-jp/hunny#11]
アプリ内に新しく hoshi005 のデータを追加します

**Comment by rbdog** [comment]
@hoshi005 
このissueの担当者に任命しました。締め切り期限はありません。よろしくお願いします。

**Comment by rbdog** [comment]
@hoshi005 
プルリクを承認したため、このissueをクローズします。
プロジェクトへ貢献、ありがとう！
