### ISSUE TITLE
[FR] k-nakahara-watahanが参加

### ISSUE THREAD

**Issue by k-nakahara-watahan** [rubydog-jp/hunny#16]
アプリ内に新しくk-nakahara-watahanのデータを追加します

**Comment by rbdog** [comment]
@k-nakahara-watahan 
このissueの担当者に割り当てました。締め切り期限はありません、対応よろしくお願いします

**Comment by rbdog** [comment]
プルリクを承認。
このissueに関するタスクは全て完了したためクローズします。ありがとうございました。
