### ISSUE TITLE
[FR] ASHIMOTOが参加

### ISSUE THREAD

**Issue by ASHIMOTO0729** [rubydog-jp/hunny#18]
アプリ内に新しく ASHIMOTO のデータを追加します

**Comment by rbdog** [comment]
@ASHIMOTO0729 
このissueの担当者に任命しました。締め切り期限はありません。よろしくお願いします。

**Comment by rbdog** [comment]
@ASHIMOTO0729 
プルリクが承認されたため、このissueをクローズします。
お疲れ様でした。
