### ISSUE TITLE
[FR]KonSan0722が参加

### ISSUE THREAD

**Issue by KonSan0722** [rubydog-jp/hunny#20]
アプリに新しくKonSan0722のデータを追加します。

**Comment by rbdog** [comment]
@KonSan0722 
このissueの担当者に任命しました。締め切りはありません。よろしくお願いします。

**Comment by rbdog** [comment]
@KonSan0722 
すみません、私の実験に付き合ってください
手順7のプッシュの直前にやって欲しいです。

下のコマンドの `アクセストークン` に自分のアクセストークンを入れて実行

```
$ git remote set-url origin https://KonSan0722:アクセストークン@github.com/KonSan0722/hunny.git
```

その後プッシュが成功するかどうかを確認したいです

**Comment by KonSan0722** [comment]
こちらも先ほど試したのですがダメでした、、

**Comment by rbdog** [comment]
次の実験お願いします！

```
git remote set-url origin https://KonSan0722@github.com/KonSan0722/hunny.git
```

からの、プッシュ

```
git push origin feat/new_cell_KonSan0722_20
```

おそらくパスワードを聞かれるので `アクセストークン` を入力します

**Comment by KonSan0722** [comment]
同じくダメですね、、

**Comment by KonSan0722** [comment]
全く同じエラー文です！
ログインパスワードでダメでアクセストークンでダメと二通り試しました、、

**Comment by KonSan0722** [comment]
これはユーザー名とかはあんまり関係ないですか？

**Comment by rbdog** [comment]
なるほど、パスワードを聞かれるところまではいけてるんですね！

**Comment by KonSan0722** [comment]
そうなんですー！なんか2021年からアクセストークンじゃないとだめみたいなやつが出てアクセストークン打ってもダメで、、みたいな笑

**Comment by rbdog** [comment]
すみません、回答忘れてました。ユーザー名は無関係です
Windowsが勝手に古い情報を保存して使ってる可能性がありますね。こちらの記事はどうでしょう？

https://qiita.com/BlackMagician/items/5a23ffb68aea591c067f

最後の `git push origin master` は `git push origin feat/new_cell_KonSan0722_20` でお願いします。

**Comment by rbdog** [comment]
@hemuwan
召喚！
なんかお二人、ちょうど同じ現象が起こってますね...笑

笑い事じゃないか。。。(でもこれで同じデータ編集してたら流石に笑います。今回のエラーとは無関係)

**Comment by KonSan0722** [comment]
git config credential.helperをするとosxkeychainと出てきました！
https://kt-media.blog/git-pushしたら403エラーが返ってきた際の対処法/
まさかこれでしょうか？

**Comment by rbdog** [comment]
今の私お手上げ状態なので、これにすがります。私のチュートリアルです。

**Comment by rbdog** [comment]
ちなみにユーザー名はすべて「ユーザーID」のことです。 `KonSan0722` を使用してください。
今回の件は `ユーザーID` 以外は関係ありません

**Comment by rbdog** [comment]
🤔アクセストークンが間違って削除されていたり、有効期限が切れたりしてないですもんね。

**Comment by rbdog** [comment]
@KonSan0722 @hemuwan
お二方、アクセストークンに権限をつけて作り直してみてもらえますでしょうか？

[アクセストークンを作成](https://github.com/settings/tokens)

<img width="930" alt="Screenshot 2023-10-24 at 23 20 23" src="https://github.com/rubydog-jp/hunny/assets/76613417/dcd49003-fa45-4996-bdb9-a1672f7e7922">

**Comment by KonSan0722** [comment]
アクセストークンは削除や期限切れはなさそうですね、、作るときはclassicで間違い無いですよね？

**Comment by KonSan0722** [comment]
一度デリートしても良さそうですか？

**Comment by rbdog** [comment]
ありがとうございます。はい、classicで大丈夫です。デリートも問題ありません！

**Comment by rbdog** [comment]
新しいアクセストークンが完成したら、

1. アクセストークン情報が入ってないURLを設定しなおす

```
git remote set-url origin https://KonSan0722@github.com/KonSan0722/hunny.git
```
2. プッシュする

```
git push origin feat/new_cell_KonSan0722_20
```

3. 質問されたらアクセストークンを入力

**Comment by KonSan0722** [comment]
きましたーーーーーーー！！！！！
うおおおおおおお！！！！

**Comment by rbdog** [comment]
大変失礼しました。チュートリアルを修正いたします
お疲れさまでした！

**Comment by KonSan0722** [comment]
トークンを作る時repoにチェックを入れてなかったからか、、
難しいですね！
サポートありがとうございました！！

**Comment by rbdog** [comment]
あとは最後の手順だけなので、ぜひプルリクお願いします！

[プルリク](https://rubydog-jp.github.io/hunny/tutorial/pull-req#pull-request-%E3%82%92%E4%BD%9C%E6%88%90)

**Comment by rbdog** [comment]
@KonSan0722 
ブランチからやり直すコマンドを一通り書きました

```
# hunnyフォルダへ移動
$ cd hunny

# 古い方が残っているかもしれないので 一旦アクセストークンをセットし直す
$ git remote add origin https://<アクセストークン>@github.com/KonSan0722/hunny.git

# 一旦メインブランチへ戻る
$ git checkout main

# 最新のデータをハニー本体から取り込んでおく
$ git pull --rebase upstream main

# 別の新しいブランチを作る
$ git checkout -b feat/new_cell_KonSan0722_again_20

# Mac なら
$ open .

# Windowsなら
$ start .

### ここで適当なデータを変更 ###

# コミット
$ git add data/cells.json
$ git commit -m "feat: new cell KonSan0722 #20"

# プッシュ
$ git push origin feat/new_cell_KonSan0722_again_20

# 以下ページからプルリクエストできるか確認
# https://github.com/rubydog-jp/hunny/pulls
```

**Comment by rbdog** [comment]
22:27 上記少し更新しました

**Comment by KonSan0722** [comment]
いけました、、、さすがすぎます、、、

**Comment by rbdog** [comment]
プルリク受け取りました！これは熱い展開
本件完了のためクローズいたします
