### ISSUE TITLE
[FR] hemuwan が参加

### ISSUE THREAD

**Issue by hemuwan** [rubydog-jp/hunny#22]
説明: アプリ内に新しく hemuwan のデータを追加します

**Comment by rbdog** [comment]
@hemuwan 
キターー

**Comment by hemuwan** [comment]
ひえええええええええええええ

**Comment by rbdog** [comment]
アクセストークンに権限をつけて、作り直してみてもらえますでしょうか？
リポジトリのところにチェックをつけます。
古いほうはデリートして問題ありません

[アクセストークンを作成](https://github.com/settings/tokens)


<br />
<img width="930" alt="Screenshot 2023-10-24 at 23 20 23" src="https://github.com/rubydog-jp/hunny/assets/76613417/d7c7a438-f9aa-4917-93d4-58b656902067">

**Comment by rbdog** [comment]
新しいアクセストークンが完成したら、

1. アクセストークン情報が入ってないURLを設定しなおす

```
git remote set-url origin https://hemuwan@github.com/hemuwan/hunny.git
```
2. プッシュする

```
git push origin feat/new_cell_hemuwan_22
```

3. 質問されたらアクセストークンを入力

**Comment by rbdog** [comment]
@hemuwan 
お疲れ様でした。色々とお手数おかけしました。完了できてよかったです。
本件クローズします。
