### ISSUE TITLE
[FR] sesamegg が参加

### ISSUE THREAD

**Issue by sesamegg** [rubydog-jp/hunny#32]
アプリ内に新しく sesamegg のデータを追加します

**Comment by rbdog** [comment]
@sesamegg 
このissueの担当者に任命しました。締め切り期限はありません。よろしくお願いします。

**Comment by rbdog** [comment]
@sesamegg 

まずは2日ほど前に修正した内容の確認からいきます！
手順1でアクセストークン作ったときに「repo」のところにチェック入れる説明が抜けていました。現在は修正済みです。

ここにチェック入れた記憶はありますでしょうか？

<img width="1380" alt="Screenshot 2023-10-26 at 18 13 09" src="https://github.com/rubydog-jp/hunny/assets/76613417/ef910513-9c35-4c41-9d34-55ea3387904f">

**Comment by rbdog** [comment]
もしも覚えがない場合はアクセストークンを作り直してください。
古い方は権限が無さすぎるトークンだったのでデリートしていただいて構いません

[アクセストークン作成](https://github.com/settings/tokens)

作り直したら以下のコマンドです

```
# アクセストークンをGitにセットし直す
$ git remote add origin https://<新しいアクセストークン>@github.com/sesamegg/hunny.git

# プッシュ
$ git push origin feat/new_cell_sesamegg_32

```

**Comment by sesamegg** [comment]
古い方のトークンの設定を確認したところチェック入っていなかったので、入れて作成しなおしました！
そのままローカルのGItを再設定しようとすると
`fatal: remote origin already exists.`
が出ましたので、
`$ git remote rm origin`
で一旦削除するとうまくいったようです。
引き続きプルリクエストをやってみます！！ご対応ありがとうございます。

**Comment by rbdog** [comment]
ありがとうございます！待ってまーす😌

**Comment by rbdog** [comment]
@sesamegg 

レビューを返しました。以下から対応お願いします
https://github.com/rubydog-jp/hunny/pull/37

**Comment by rbdog** [comment]
関連するタスクが全て完了したため本issueをクローズします。ありがとうございました。
