### ISSUE TITLE
[FR] nagadaruが参加

### ISSUE THREAD

**Issue by nagadaru** [rubydog-jp/hunny#4]
アプリ内に新しく nagadaru のデータを追加します

**Comment by rbdog** [comment]
@nagadaru 
タスクの担当者を割り当てました。期限はありません。対応よろしくお願いします

**Comment by rbdog** [comment]
1点、ダブルクォーテーションが抜けていたのでプルリク承認のときに追加してコミットしました。
 
 - Bad
 
 ```
 {
    "github_id": nagadaru,
    "text": naga
 },
 ```
 
 - Good
 
 ```
 {
    "github_id": "nagadaru",
    "text": "naga"
 },
 ```

**Comment by rbdog** [comment]
@nagadaru 
全タスクが完了したためissueクローズします。ありがとう！
