### ISSUE TITLE
[FR]Fukungaが参加

### ISSUE THREAD

**Issue by Fukunga** [rubydog-jp/hunny#48]
今度こそ

**Comment by rbdog** [comment]
このissueの担当者に任命しました、よろしくお願いします✨

**Comment by Fukunga** [comment]
このあと何すればいいんですかね？😅

**Comment by rbdog** [comment]
@Fukunga 
あれ？！　もしかして　ここにコメントした最後の手順
https://github.com/Fukunga/hunny/issues/1

「プルリクエストの作成」は、もう出来なくなっちゃってますかね？
コード変更してないから、同じプルリクエストを2回できないってことかな？？？

もしそうだとしたら、私のコメントミスなので、古いプルリクエストを復活してみます
申し訳ないです🙇

**Comment by rbdog** [comment]
このメッセージを確認いただけましたら、下のボタンから このissue をクローズしてください
以上で全工程が終了です。お疲れ様でした！
