### ISSUE TITLE
[FR]keigorouが参加

### ISSUE THREAD

**Issue by keigorou** [rubydog-jp/hunny#49]
アプリ内に新しくkeigorouのデータを追加します

**Comment by rbdog** [comment]
@keigorou 
このissueの担当者に任命しました。締め切り期限はありません。よろしくお願いします。

**Comment by rbdog** [comment]
本件に関する全ての作業が完了したため、このissueをクローズします。
お疲れ様でした🎉

**Comment by keigorou** [comment]
いつもYOUTUBE見ていて、アプリ作りの参考にさせてもらってます！
このhunnyも面白い試みですね！

**Comment by rbdog** [comment]
@keigorou 
ありがとうございます。よろしければこの流れで他のOSSプロジェクトへも参加していただければ幸いです
お待ちしております👍
https://comet.rubydog.jp/docs-jp/oss-contributing/
