### ISSUE TITLE
[FR] チュートリアル: 後片付けの手順を追記する

### ISSUE THREAD

**Issue by rbdog** [rubydog-jp/hunny#5]
GitHubアカウントに不要なリポジトリが残るのを嫌う人がいるかもしれない。
チュートリアルが終わった後、リポジトリの削除の手順を ~~スクショ付き~~ で追加。

**Comment by k-nakahara-watahan** [comment]
アプリ内に新しくk-nakahara-watahanのデータを追加します

**Comment by rbdog** [comment]
パソコンの中の `hunny` フォルダを削除。
再び参加するときは 手順3 のクローンが必要になります。

次に GitHub で自分のアカウントの `hunny` を削除。
再び参加するときは 手順3 のフォークが必要になります。

https://github.com/<ユーザーID>/hunny/settings

下までスクロール

Delete this repository

本当に削除して良いか確認されるので
<ユーザーID>/hunny
と入力

**Comment by rbdog** [comment]
203 Q として追加
