### ISSUE TITLE
[FR] suittizihouが参加

### ISSUE THREAD

**Issue by suittizihou** [rubydog-jp/hunny#54]
アプリ内にたらしく suittizihou のデータを追加します

**Comment by rbdog** [comment]
@suittizihou 
このissueの担当者に任命しました。締め切り期限はありません。よろしくお願いします。

**Comment by rbdog** [comment]
@suittizihou 
プルリクまでの作業が早くて驚きました。
本件に関する全ての作業が完了したため、このissueをクローズします。
お疲れ様でした。
