### ISSUE TITLE
[FR] pigpigpigs が参加

### ISSUE THREAD

**Issue by pigpigpigs** [rubydog-jp/hunny#56]
アプリ内に新しく pigpigpigs のデータを追加します

**Comment by rbdog** [comment]
@pigpigpigs 
このissueの担当者に任命しました。締め切り期限はありません。よろしくお願いします。

**Comment by rbdog** [comment]
本件に関する全ての作業が完了したため、このissueをクローズします。
お疲れ様でした🥳
