### ISSUE TITLE
[FR]shogoisajiが参加

### ISSUE THREAD

**Issue by shogoisaji** [rubydog-jp/hunny#9]
アプリ内に新しく shogoisaji のデータを追加します

**Comment by rbdog** [comment]
@shogoisaji 
このissueの担当者に割り当てました。期限はありません。対応よろしくお願いします

**Comment by shogoisaji** [comment]
remote: Permission to shogoisaji/hunny.git denied to shogoisaji.
fatal: unable to access 'https://github.com/shogoisaji/hunny.git/': The requested URL returned error: 403

チュートリアルを参考に2回pushまで行いましたが、ここで止まってしまいます...
どのような何が原因か分かりますでしょうか？
※ユーザーIDが間違っていましたので訂正しました

**Comment by rbdog** [comment]
@shogoisaji 

このコマンドを入力してからもう一度 push してみていただけますでしょうか？

```
git remote set-url origin https://<アクセストークン>@github.com/shogoisaji/hunny.git
```

アクセストークンは秘密なので、自分のものを入れてみてくださいませ

例

```
git remote set-url origin https://ghp_Abcd1234Abcd1234@github.com/shogoisaji/hunny.git
```

**Comment by shogoisaji** [comment]
変化なしです...
同様のエラーが出ます。

**Comment by rbdog** [comment]
@shogoisaji 

なるほど、ではこちらではどうでしょうか？  
何かパスワードを聞かれたらアクセストークンを入力してみてください

```
$ git remote set-url origin https://shogoisaji@github.com/shogoisaji/hunny.git
```

**Comment by shogoisaji** [comment]
上記で行けたっぽいです！

**Comment by rbdog** [comment]
お手数おかけしました。チュートリアルを修正いたします。

**Comment by rbdog** [comment]
チュートリアルの訂正を完了しました。
タスクが完了したので このissueをクローズします。
